### ISSUE TITLE
ARM support: use rsa-compat alongside node-forge

### ISSUE THREAD

**Issue by coolaj86** [insightfuls/le-tls-sni#1]
I created [`rsa-compat`](https://github.com/Daplie/rsa-compat.js) because I wanted letsencrypt to work both on ARM devices (low cpu, needs native rsa) and Windows (needs to work without compiler).

If you swap out forge for rsa-compat it'll "just work" in the best way, regardless of the platform. It uses either ursa or forge depending on what's available.

**Comment by coolaj86** [comment]
I see that you still need forge directly for some of the certificate stuff, but generating the keypair is covered by `rsa-compat`.

**Comment by insightfuls** [comment]
Yes. The reason I didn't use `rsa-compat` was that I needed additional certificate stuff. I didn't realise ARM and Windows compatibility was the reason behind `rsa-compat`. So I take it that `node-forge` handles the Windows scenario. What is the reasoning behind using `ursa`/native on ARM? Is it simply for speed because there are fewer CPU resources available? Generating the keypair is the most intensive part of the whole deal, so I guess using `rsa-compat` would address that as long as there's no reason not to use `node-forge` for the certificate stuff.

**Comment by insightfuls** [comment]
I'm also planning to generate just one key and use it for all self-signed certs. There's no reason to generate a new key for each new cert. They don't really certify anything, they just demonstrate to the ACME server that something can be served by the server in DNS, and the key isn't used for anything else. So that will speed things up, too.

**Comment by coolaj86** [comment]
Yeah, it took 20 minutes to generate a key on a RPi 1 with forge.

BTW: https://wefunder.com/daplie <-- that's what we're doing and why we built the letsencrypt lib.

**Comment by insightfuls** [comment]
I like the look of your project. Here in Australia our Internet speed isn't very amenable to it, though, on the whole. I'm definitely a 'keep it under your own control' kind of guy, though, so it does appeal to me. There are lots of different directions you could take it, too.

**Comment by coolaj86** [comment]
[OT: home cloud]

Speed isn't very important, actually - only that it's always on.

For download we're building out the apps to cache media on your devices. A lot of that transfer happens in your home on WiFi or Ethernet, so mobile speed isn't very important.

The upload speed from your home is relatively unimportant as well since it's always on and it's okay for something to take a while to sync.

The apps we're currently building are based around consumer and home applications and even most small businesses don't even get a few million visits to their website per month, so I'll be surprised if speed becomes a limiting factor until we scale to mid-sized business applications.
